import { Geist, } from "next/font/google";
import "./globals.css";

// Load fonts with Next.js optimization
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});






export const metadata = {
  title: "VeJoBizz",
  description: "Generated by Vignesh Kumar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>

        {children}
      </body>
    </html>
  );
}
